wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ag105mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ag107mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ag109mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ag111mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/al26mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/al27mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ar36mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ar37mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ar38mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ar39mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ar40mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ar42mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/as71mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/as72mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/as73mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/as74mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/as75mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/as76mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/as77mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/au194mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/au195mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/au196mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/au197mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/au198mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/au199mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba128mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba130mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba131mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba132mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba133mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba134mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba135mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba136mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba137mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba138mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ba140mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/bi205mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/bi206mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/bi207mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/bi208mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/bi209mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/br77mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/br79mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/br81mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/br82mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca40mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca41mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca42mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca43mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca44mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca45mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca46mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca47mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ca48mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd106mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd108mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd109mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd110mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd111mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd112mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd113mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd114mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd115mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cd116mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce136mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce138mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce139mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce140mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce141mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce142mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce143mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ce144mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cl35mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cl36mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cl37mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/co56mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/co57mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/co58mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/co59mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/co60mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cr50mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cr51mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cr52mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cr53mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cr54mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs129mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs131mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs132mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs133mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs134mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs135mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs136mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cs137mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cu63mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cu65mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/cu67mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy154mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy156mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy158mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy159mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy160mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy161mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy162mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy163mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy164mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/dy166mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er162mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er164mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er166mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er167mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er168mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er169mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er170mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/er172mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu145mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu146mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu147mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu148mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu149mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu151mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu152mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu153mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu154mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu155mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/eu156mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe53mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe54mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe55mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe56mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe57mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe58mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe59mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/fe60mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ga67mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ga69mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ga71mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd146mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd147mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd148mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd149mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd150mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd151mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd152mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd153mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd154mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd155mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd156mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd157mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd158mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/gd160mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge68mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge69mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge70mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge71mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge72mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge73mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge74mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ge76mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf173mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf174mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf175mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf176mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf177mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf178mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf179mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf180mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf181mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hf182mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg194mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg196mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg197mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg198mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg199mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg200mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg201mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg202mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg203mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/hg204mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ho163mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ho165mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ho166mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/i124mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/i125mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/i126mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/i127mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/i129mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/i131mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/in111mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/in113mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/in115mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ir188mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ir189mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ir190mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ir191mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ir192mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ir193mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/k39mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/k40mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/k41mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr78mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr79mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr80mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr81mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr82mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr83mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr84mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr85mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/kr86mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/la137mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/la138mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/la139mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/la140mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu169mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu170mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu171mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu172mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu173mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu174mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu175mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu176mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/lu177mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mn52mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mn53mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mn54mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mn55mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo92mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo93mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo94mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo95mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo96mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo97mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo98mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo99mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/mo100mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nb91mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nb92mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nb93mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nb94mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nb95mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd140mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd142mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd143mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd144mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd145mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd146mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd147mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd148mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/nd150mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni56mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni57mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni58mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni59mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni60mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni61mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni62mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni63mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni64mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ni66mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os184mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os185mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os186mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os187mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os188mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os189mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os190mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os191mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os192mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os193mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/os194mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/p31mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/p32mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/p33mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pb202mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pb203mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pb204mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pb205mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pb206mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pb207mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pb208mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd100mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd102mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd103mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd104mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd105mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd106mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd107mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd108mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pd110mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm143mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm144mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm145mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm146mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm147mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm148mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm149mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pm151mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/po206mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/po208mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/po209mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pr141mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pr143mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt190mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt191mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt192mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt193mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt194mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt195mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt196mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/pt198mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rb83mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rb84mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rb85mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rb86mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rb87mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/re182mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/re183mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/re184mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/re185mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/re186mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/re187mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/re189mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rh99mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rh101mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rh102mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rh103mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/rh105mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru96mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru97mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru98mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru99mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru100mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru101mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru102mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru103mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru104mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ru106mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/s32mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/s33mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/s34mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/s35mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/s36mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb119mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb121mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb122mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb123mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb124mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb125mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb126mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sb127mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sc45mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sc46mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sc47mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sc48mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se72mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se74mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se75mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se76mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se77mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se78mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se79mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se80mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/se82mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/si28mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/si29mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/si30mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/si32mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm144mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm145mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm146mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm147mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm148mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm149mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm150mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm151mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm152mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm153mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sm154mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn112mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn113mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn114mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn115mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn116mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn117mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn118mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn119mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn120mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn121mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn122mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn123mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn124mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn125mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sn126mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr82mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr83mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr84mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr85mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr86mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr87mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr88mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr89mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/sr90mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ta177mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ta179mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ta180mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ta181mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ta182mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ta183mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb153mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb155mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb156mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb157mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb158mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb159mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb160mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tb161mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tc96mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tc97mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tc98mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tc99mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te118mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te120mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te121mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te122mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te123mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te124mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te125mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te126mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te128mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te130mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/te132mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ti44mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ti46mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ti47mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ti48mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ti49mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/ti50mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tl200mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tl201mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tl202mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tl203mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tl204mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tl205mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tm165mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tm167mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tm168mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tm169mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tm170mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tm171mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/tm172mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/v48mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/v49mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/v50mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/v51mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w178mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w180mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w181mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w182mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w183mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w184mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w185mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w186mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/w188mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe124mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe126mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe127mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe128mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe129mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe130mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe131mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe132mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe133mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe134mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/xe136mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/y87mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/y88mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/y89mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/y90mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/y91mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb166mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb168mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb169mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb170mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb171mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb172mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb173mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb174mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb175mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/yb176mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zn64mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zn65mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zn66mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zn67mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zn68mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zn70mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zn72mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr88mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr89mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr90mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr91mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr92mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr93mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr94mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr95mp.ndl
wget http://www.oecd-nea.org/dbforms/data/eva/evatapes/mendl_2p/zr96mp.ndl
